import { Position, MarkerType } from "@xyflow/react";

// 定義節點 (注意 data.label 裡面可以直接放 JSX / React 元件)
export const guide_nodes = [
  {
    id: "1",
    type: "custom",
    position: { x: 350, y: 0 },
    data: {
      label: "Loss on training data",
      targetPosition: Position.Top,
      sourcePosition: Position.Bottom,
      width: "150px",
      height: "120px",
    },
  },
  {
    id: "1_o",
    type: "custom",
    position: { x: 400, y: 50 },
    data: {
      targetPosition: Position.Top,
      sourcePosition: Position.Bottom,
      erase_bg: true,
      erase_border: true,
    },
  },
  {
    id: "2",
    type: "custom",
    position: { x: 200, y: 100 },
    data: {
      targetPosition: Position.Top,
      sourcePosition: Position.Bottom,
      width: "50px",
      erase_bg: true,
      erase_border: true,
    },
  },
  {
    id: "3",
    type: "custom",
    position: { x: 600, y: 100 },
    data: {
      label: "Loss on testing data",
      targetPosition: Position.Top,
      sourcePosition: Position.Bottom,
      width: "150px",
      height: "120px",
    },
  },
  {
    id: "3_o",
    type: "custom",
    position: { x: 700, y: 150 },
    data: {
      targetPosition: Position.Top,
      sourcePosition: Position.Bottom,
      width: "150px",
      height: "120px",
      erase_bg: true,
      erase_border: true,
    },
  },
  {
    id: "4",
    type: "custom",
    position: { x: 0, y: 200 },
    data: {
      label: "Make model complex",
      targetPosition: Position.Top,
      sourcePosition: Position.Bottom,
      width: "150px",
      height: "120px",
    },
  },
  {
    id: "4_o",
    type: "custom",
    position: { x: 100, y: 250 },
    data: {
      targetPosition: Position.Top,
      sourcePosition: Position.Bottom,
      erase_bg: true,
      erase_border: true,
    },
  },
  {
    id: "5",
    type: "custom",
    position: { x: 300, y: 200 },
    data: {
      label: "Optimization",
      targetPosition: Position.Top,
      sourcePosition: Position.Bottom,
      width: "150px",
    },
  },
  {
    id: "6",
    type: "custom",
    position: { x: 500, y: 200 },
    data: {
      targetPosition: Position.Top,
      sourcePosition: Position.Bottom,
      width: "50px",
      erase_bg: true,
      erase_border: true,
    },
  },
  {
    id: "7",
    type: "custom",
    position: { x: 850, y: 200 },
    data: {
      label: "Goal",
      targetPosition: Position.Top,
      sourcePosition: Position.Bottom,
      width: "100px",
    },
  },
  {
    id: "8",
    type: "custom",
    position: { x: 225, y: 350 },
    data: {
      label: "Mode training data, Data augmentation, Make model simpler",
      targetPosition: Position.Top,
      sourcePosition: Position.Bottom,
      width: "300px",
      height: "120px",
    },
  },
  {
    id: "9",
    type: "custom",
    position: { x: 600, y: 350 },
    data: {
      label: "Mismatch",
      targetPosition: Position.Top,
      sourcePosition: Position.Bottom,
      width: "150px",
    },
  },
  {
    id: "_",
    type: "custom",
    position: { x: 600, y: 400 },
    data: {
      targetPosition: Position.Top,
      sourcePosition: Position.Bottom,
      erase_bg: true,
      erase_border: true,
    },
  },
];

// 定義連線 (帶有動畫的箭頭)
export const guide_edges = [
  {
    id: "e1-2",
    source: "1",
    target: "2",
    type: "straight",
    animated: true,
    label: "large",
    labelStyle: { fill: "#7c9fa8", fontWeight: 700, fontSize: "20px" },
    style: { stroke: "#7c9fa8", strokeWidth: 3 },
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
      color: "#7c9fa8",
    },
  },
  {
    id: "e1-3",
    source: "1_o",
    target: "3",
    type: "straight",
    animated: true,
    label: "small",
    labelStyle: { fill: "#7c9fa8", fontWeight: 700, fontSize: "20px" },
    style: { stroke: "#7c9fa8", strokeWidth: 3 },
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
      color: "#7c9fa8",
    },
  },
  {
    id: "e2-4",
    source: "2",
    target: "4",
    type: "straight",
    animated: true,
    label: "model bias",
    labelStyle: { fill: "#7c9fa8", fontWeight: 700, fontSize: "20px" },
    style: { stroke: "#7c9fa8", strokeWidth: 3 },
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
      color: "#7c9fa8",
    },
  },
  {
    id: "e2-5",
    source: "2",
    target: "5",
    type: "straight",
    animated: true,
    label: "optimization",
    labelStyle: { fill: "#7c9fa8", fontWeight: 700, fontSize: "20px" },
    style: { stroke: "#7c9fa8", strokeWidth: 3 },
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
      color: "#7c9fa8",
    },
  },
  {
    id: "e3-6",
    source: "3",
    target: "6",
    type: "straight",
    animated: true,
    label: "large",
    labelStyle: { fill: "#7c9fa8", fontWeight: 700, fontSize: "20px" },
    style: { stroke: "#7c9fa8", strokeWidth: 3 },
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
      color: "#7c9fa8",
    },
  },
  {
    id: "e3-7",
    source: "3_o",
    target: "7",
    type: "straight",
    animated: true,
    label: "small",
    labelStyle: { fill: "#7c9fa8", fontWeight: 700, fontSize: "20px" },
    style: { stroke: "#7c9fa8", strokeWidth: 3 },
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
      color: "#7c9fa8",
    },
  },
  {
    id: "e6-8",
    source: "6",
    target: "8",
    type: "straight",
    animated: true,
    label: "overfitting",
    labelStyle: { fill: "#7c9fa8", fontWeight: 700, fontSize: "20px" },
    style: { stroke: "#7c9fa8", strokeWidth: 3 },
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
      color: "#7c9fa8",
    },
  },
  {
    id: "e6-9",
    source: "6",
    target: "9",
    type: "straight",
    animated: true,
    label: "mismatch",
    labelStyle: { fill: "#7c9fa8", fontWeight: 700, fontSize: "20px" },
    style: { stroke: "#7c9fa8", strokeWidth: 3 },
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
      color: "#7c9fa8",
    },
  },
  {
    id: "e4-8",
    source: "4_o",
    target: "8",
    animated: true,
    label: "trade-off",
    labelStyle: { fill: "#c14a38", fontWeight: 700, fontSize: "20px" },
    style: { stroke: "#c14a38", strokeWidth: 3 },
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
      color: "#7c9fa8",
    },
  },
];
